### ISSUE TITLE
"Error parsing Command"

### ISSUE THREAD

**Issue by garyb** [kRITZCREEK/pscid#1]
I'm having some trouble getting this to work with SlamData, it seems this happens:

```
Checking /Users/gary/GitHub/slamdata/src/Quasar/Aff.purs
Error parsing Command.
```

For any file I modify. I have the PS executables built from `48e2766845bcb304d0842b257b97965c28738ef9` on master, so this definitely has the changes in it.

**Comment by kritzcreek** [comment]
Could you try `npm i -g pscid` again? It should show some ascii art in the newest version which has fixes.

**Comment by garyb** [comment]
That's the version I'm using (1.4.0).

**Comment by garyb** [comment]
Interesting, it seems like it works on Windows. Almost... having a little unicode problem now, I'll open a separate issue for that on the purescript repo.

**Comment by kritzcreek** [comment]
@garyb that sounds very strange indeed... maybe try setting a different `-p`ort?

I have it running on both OSX and arch...

**Comment by garyb** [comment]
Same thing with different port values. :confused: 

The message is coming from the server though, so I don't think it's a connectivity issue: https://github.com/purescript/purescript/blob/8bab5090ce3559d89c10c34e240356a5b371a489/psc-ide-server/Main.hs#L137

**Comment by kritzcreek** [comment]
Okay debug land: Can you start psc-ide-server with the --debug flag in a separate terminal and then specify the -p of pscid to be 4242 ?

**Comment by garyb** [comment]
Strange, it behaves differently now:

```
Checking /Users/gary/GitHub/slamdata/src/Quasar/Aff.purs
[1/1 UnknownModule] 

  Unknown module SlamData.Prelude
```

Debug output:

```
[Debug] Accepted a connection @(main:Main psc-ide-server/Main.hs:146:5)
[Debug] {"params":{"dependencies":[],"modules":[]},"command":"load"} @(main:Main psc-ide-server/Main.hs:156:9)

[Debug] Inserting Module: ... snip 600 of these ...

[Debug] Accepted a connection @(main:Main psc-ide-server/Main.hs:146:5)
[Debug] {"command":"cwd"} @(main:Main psc-ide-server/Main.hs:156:9)
[Debug] Accepted a connection @(main:Main psc-ide-server/Main.hs:146:5)
[Debug] {"params":{"file":"/Users/gary/GitHub/slamdata/src/Quasar/Aff.purs"},"command":"rebuild"} @(main:Main psc-ide-server/Main.hs:156:9)
```

**Comment by kritzcreek** [comment]
It seems like you have an old psc-ide-server lying around... Maybe from an old npm install of the compiler?

**Comment by garyb** [comment]
Aargh. Haha. Thanks, sorry for the rabbit hole. I just switched to using Stack on here at the weekend but hadn't reopened my terminal tabs after updating the `PATH`.

**Comment by kritzcreek** [comment]
It's all good^^ The real issue is that the clients should check for a compatible version or at least include version information in the errors
