### ISSUE TITLE
Non-JSON errors (circular imports)

### ISSUE THREAD

**Issue by nwolverson** [kRITZCREEK/pscid#20]
When rebuilding a file with circular imports, prior to 0.8.0 it seems pscid would print the warning `There was a cycle in the dependencies`, while from 0.8.0 onwards I see `Failed to parse errors`.

This is resulting from a psc-ide-server error which is a string instead of a JSON error (which I think is wrong anyway):

`{result: "There was a cycle in the dependencies", resultType: "error"}`

This used to be logged due to this line: https://github.com/kRITZCREEK/pscid/blob/264bf9b5fb224995677bb0d0a27faa462e5abbc1/src/Pscid/Psa.purs#L83

I have the same issue in https://github.com/nwolverson/atom-ide-purescript/issues/116 (which I do intend to fix) - I guess there could be a change on the server side, what's your thought?

**Comment by kritzcreek** [comment]
So the JSON instance for the circular dependency error inside the compiler is buggy?

**Comment by nwolverson** [comment]
In regular psc this is a specific error:

https://github.com/purescript/purescript/blob/827b710e343c5e0692d6174ca75a20ad39e8b79e/src/Language/PureScript/Errors.hs#L643

In psc-ide this is a `GeneralError`:
https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Ide/Rebuild.hs#L148

Of course there are other `GeneralError` style errors - so regardless may want to consume these on the client side. I've made a change for atom to show this as a standard linter error when rebuilding.

(I think rebuild is unique in having a formatted error case, for every other command in the psc-ide protocal there is just the standard string error?)

**Comment by kritzcreek** [comment]
Oh now I see, thank you. We should definitely wrap the cycle in modules error in the proper JSON error format that the compiler emits. I can take a look later unless you want to.
