### ISSUE TITLE
--src-path

### ISSUE THREAD

**Issue by bkonkle** [kRITZCREEK/pscid#21]
I'm transpiling my FFI modules from `src` with babel, outputting them (along with the .purs files) to `lib`. I run pulp build with the `--src-path lib` option so that it looks in `lib` instead of `src`. Can we expose this option in `pscid`?

**Comment by bkonkle** [comment]
Looks like this will be an issue on `atom-ide-purescript` as well. Maybe it's just not worth it.

**Comment by bkonkle** [comment]
Maybe I'll approach it in a different way. I can gitignore `src/*.js`, then compile from `lib` into `src` prior to running the build.

**Comment by kritzcreek** [comment]
Does the `--include` option work for you? something like `pscid --include "lib;test" --test`

**Comment by nwolverson** [comment]
(for atom you can configure the full build command as you like, eg your pulp command line, and source globs for goto-def. unfortunately the config is global)

**Comment by bkonkle** [comment]
Thanks for the suggestions! I haven't had a chance to try the `--include` option yet, but I suspect psc will find the ES'15 source in `src`, attempt to parse it, and choke on the first `import` statement. At that point, it throws an error rather than falling back to directories in `--include`, right?

**Comment by kritzcreek** [comment]
I made it so that the list for `--include` is explicit so you can exclude folders like `src/` or `test/` if you want to.

eg. `pscid --include lib` will only watch the `lib/` directory

**Comment by bkonkle** [comment]
Great! Unfortunately, the problem I end up having is that now my changes to the `src` directory aren't detected. I tried `--include=lib;src` but it still didn't detect changes to `src`, and I realized that's not a good idea anyway because the compiler will detect duplicate PureScript module definitions.

**Comment by bkonkle** [comment]
This is because I was being stupid and still trying to build out of `src` and not `lib`. I think I fixed it, and I'll post my final build setup later.

**Comment by bkonkle** [comment]
AH, but if I have Babel watch, it will copy the changed files into `lib`, triggering the pscid build! \o/ Thanks for the help!
