### ISSUE TITLE
0.11 compatibility

### ISSUE THREAD

**Issue by nwolverson** [kRITZCREEK/pscid#28]
Running with 0.11 toolchain installed, pscid will run a full build fine, but hangs on file changes.

Not quite sure why the hanging occurs, but anyway will need to switch to talking to purs rather than psc-ide-server.

Currently working on this including building with 0.11.

**Comment by nwolverson** [comment]
Is this fixed with #29 ?

**Comment by kritzcreek** [comment]
@rightfold is using it with 0.11 right?

**Comment by no-longer-on-githu-b** [comment]
Yes and it works great. Probably PEBKAC :trollface:

**Comment by kritzcreek** [comment]
great thanks!
