### ISSUE TITLE
ENOENT when attempting to build on Windows

### ISSUE THREAD

**Issue by garyb** [kRITZCREEK/pscid#3]
Because Windows is awesome, `spawn pulp` fails, as it's `pulp.cmd`.

Also the message states that `npm run build` is attempted, but I think it's just using `pulp`, isn't it?

**Comment by kritzcreek** [comment]
@garyb it runs pulp build if it doesn't find a `scripts.build` inside your package.json

https://github.com/kRITZCREEK/pscid/blob/b08d8a7afec121dbf91f2d4ca79115c9efef0be5/src/Pscid/Options.js

and ARGH WINDOWS

**Comment by garyb** [comment]
Ah ok!

**Comment by kritzcreek** [comment]
Should be fixed with https://github.com/kRITZCREEK/pscid/commit/476d95edd7342722a68725b8a82355e202e904d2
