### ISSUE TITLE
function signature split onto two lines

### ISSUE THREAD

**Issue by adarqui** [kRITZCREEK/pscid#31]
Not sure if these should be posted here or the suggest repo. Here's another one i've encountered:

```
container_ :: Array (HTML _ _) -> HTML _ _
container_ = container []
```

Gives the warning:

```
[1/1 WildcardInferredType] src/LN/Helpers/Halogen/Util.purs:134:27

  134  container_ :: Array (HTML _ _) -> HTML _ _
                                 ^

  Wildcard type definition has the inferred type

    t0

  in value declaration container_

  where t0 is an unknown type


Press s to automatically apply the suggestion.
```

Then when I apply the auto suggestions, it becomes:

```
container_ :: Array (HTML _
 _) -> HTML _ _
container_ = container []
```

**Comment by kritzcreek** [comment]
All the suggestion related machinery is provided by https://github.com/nwolverson/purescript-suggest, so I'd suggest to raise that issue over there.

**Comment by adarqui** [comment]
Cool thanks. I'll post it there later. Closing.
