### ISSUE TITLE
reconsider the `b` command

### ISSUE THREAD

**Issue by rnons** [kRITZCREEK/pscid#32]
Hi, I only start using `pscid` today. I am very happy with it, except the behavior of the `b` command.

I am using `pscid` with `webpack`, my ***package.json*** looks like this

```
{
  "scripts": {
    "build": "webpack -p --progress",
    "start": "webpack-dev-server --progress"
  },
  ...
} 
```

During dev, I want to run `npm run start` in one terminal pane, and `pscid` in another pane. But with the current behavior of `b`, I have to run `pulp build` before `pscid` or change the `build` script in ***package.json***.

In my opinion, `pscid` should not interfere with package.json.

Thank you.

**Comment by kritzcreek** [comment]
With #38 you can now use the `pscid:build` command inside package.json which takes precedence over the build command, so we don't take the namespace for these common commands.
