### ISSUE TITLE
Failed to start psc-ide-server on Windows

### ISSUE THREAD

**Issue by jmn** [kRITZCREEK/pscid#40]
I feel like I'm missing something obvious here but pscid does not start. Unsure how to troubleshoot. ?

```
...\git\ysgf>pscid
Starting purs ide server
Failed to start psc-ide-server
```

**Comment by kritzcreek** [comment]
That's what I get for being sloppy with error handling... Could you try again with v2.5.2 and see if we get more helpful error output?

**Comment by jmn** [comment]
```
Starting purs ide server
Failed to start psc-ide-server with: psc-ide-server error
```
I can run `purs ide server` fine.

**Comment by kritzcreek** [comment]
More swallowed errors 🎉 Try again with v2.5.3? :D

**Comment by jmn** [comment]
```
Starting purs ide server
Failed to start psc-ide-server with: psc-ide-server error:{ code: ENOENT, errno: ENOENT, syscall: spawn purs }
```

**Comment by kritzcreek** [comment]
Okay, so it looks like we're running into path issues... 

Did you install purescript through npm?
Could you try putting one of the binaries from the release page on your path?

(I suspect it's something about the `.cmd` wrappers that the npm installer uses and that we'll have to do shell expansion somewhere)

**Comment by jmn** [comment]
Yes I installed purescript using npm.

If I copy the purs binary from a release package into a directory on PATH, it works!

**Comment by yevk** [comment]
I have the same problem.
On Windows 10, installed purescript and pscid globally using NPM.
Tried running in Windows CMD, Cmder/ConEmu bash, Git Bash. Doesn't work.
`C:\Users\user\AppData\Roaming\npm` is in PATH. Also tried copying `purs` and `purs.cmd` from that dir to another dir in PATH and still got the error.

**Comment by kritzcreek** [comment]
@yevk Could you please make a new issue and include the errors you're getting as well as the output of `pscid --version` and `where.exe pscid`?
