### ISSUE TITLE
pscid --include is not working correctly

### ISSUE THREAD

**Issue by rinn7e** [kRITZCREEK/pscid#41]
I'm not sure what cause this or I may have missed any steps but `pscid --include` is not working.

I have some purescript files in `lib` dir. 
Running `pulp build --include lib` show a successful build.
However running `pscid --include lib` then press b for the full build show the build error.

**Comment by kritzcreek** [comment]
Yeah, so far the `--I` flag is only used to specify additional directories for the watcher, it doesn't get passed on to `pulp build`. A fix for now would be to specify the correct `pulp` incantation inside a `package.json` in your project under scripts with the key `pscid:build`.

A PR to automatically pass the `-I` options on to `pulp build` by default would be welcome!

**Comment by jamieyung** [comment]
#42

**Comment by jamieyung** [comment]
I'm a bit new to open source PR procedure, apologies if I'm doing things the wrong way!

I meant to reference the PR I made to address this issue :P

**Comment by kritzcreek** [comment]
Published as 2.5.4
