### ISSUE TITLE
pscid doesn't recognize psc-package path?

### ISSUE THREAD

**Issue by sharno** [kRITZCREEK/pscid#49]
We have a project using psc-package. After installing the packages and initiating `pulp build` succeeds, pscid just gives me this error on any file I try to edit:

I tried to specify explicitly the paths to include which are `src` and `.psc-package` but it still gives the same error

```
  47  import Prelude
      ^^^^^^^^^^^^^^

  Module Prelude was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.
```

**Comment by kritzcreek** [comment]
`pscid` only cares about your `output/` folder, the source directories don't matter. Do you maybe have a version mismatch between the compiler binary (`purs`) `pulp` calls vs the one `pscid` calls?

**Comment by sharno** [comment]
That's right, I had 2 different versions of `pulp` I think one global and one local for the project. I needed to run the local one instead to generate the output folder before starting pscid.

That solves it, thanks!

**Comment by kritzcreek** [comment]
Glad this worked out :)
