### ISSUE TITLE
Spago support

### ISSUE THREAD

**Issue by masaeedu** [kRITZCREEK/pscid#50]
Hi there. I'm working on a project where the tooling is based on [spago](https://github.com/spacchetti/spago). Is there a way I can use pscid but use spago for producing the build information? I'm not sure of the internals, but it seems to have a `--json-errors` mode that perhaps produces compatible output with what `pulp` would produce?

**Comment by kritzcreek** [comment]
`pscid` uses `purs ide` to produce the build information on save. It's only the hit the `b` button and trigger a full build that calls `pulp`. Are you asking for that command to automatically pick up whether `pscid` was started in a spago project?

That can be achieved right now by adding a `pscid:build` command to `package.json` that invokes spago in the appropriate way. I think I'd accept a PR that does the auto detection on startup though.
