### ISSUE TITLE
fails with error on build

### ISSUE THREAD

**Issue by srghma** [kRITZCREEK/pscid#52]
I'm trying to make nix package for this project

but it fails with an error on `npm build`

```
CompiliError found:
in module Type.Row
at bower_components/purescript-typelevel-prelude/src/Type/Row.purs:4:5 - 4:24 (line 4, column 5 - line 4, column 24)

  Export for type Prim.RowList.Cons conflicts with type class Prim.Row.Cons


See https://github.com/purescript/documentation/blob/master/errors/ExportConflict.md for more information,
or to contribute content related to this error.
```

https://github.com/justinwoo/easy-purescript-nix/pull/50/files#diff-ddebee874da1288cdd3399af004801fcR23

https://github.com/justinwoo/easy-purescript-nix/pull/50

_____

Probably the `bower update` could fix this

N.B.

we could add the code for making the nix package to this repo

**Comment by kRITZCREEK** [comment]
This essentially means packages need to be updated for 0.13, but that'll have to wait until the NPM package is updated for that. https://github.com/purescript-contrib/node-purescript/pull/69

I'm probably not going to accept any nix stuff into this repo as I'm not currently using it for my personal projects. That might totally change in the future.

**Comment by kRITZCREEK** [comment]
pscid builds with 0.13 now
