### ISSUE TITLE
feature request: allow eval

### ISSUE THREAD

**Issue by Benjmhart** [kRITZCREEK/pscid#63]
I'd like to have a feature similar to the one created for ghcid by this PR:

https://github.com/ndmitchell/ghcid/pull/248

in short,  it creates a feature flag which enables a special comment which tells the repl to evaluate something on each reload, 

some examples
```
-- $> 1+1

            -- outputs result 2

-- $> :t myVar
      -- outputs String and the accompanying type information
```

so in short, it passes commands directly to the repl immediately after the JIT compilation is complete and the module is loaded. however these comments are written directly in the file and as a result, can easily be adjusted during development.

**Comment by kritzcreek** [comment]
Hey :)

It makes total sense for ghcid to provide that feature, since its backed by a GHCI session that knows how to execute Haskell bytecode.

On the other hand pscid is backed by an instance of the ide server, which does not contain an execution environment for PureScript (a node process) and there's no such thing as PureScript bytecode. So I fear this is out of scope for pscid.

If you just care about the executing on reload part, you can use the `--test` flag and make it run something like `node interactive.js` where `interactive.js` reads something like:
```
require("./output/MyModule").functionIWantToTest()
```

**Comment by Benjmhart** [comment]
i'm actually more interested in being able to dynamicly request type information during development rather than running tests - is that plausible with the language server?

see the second example

**Comment by Benjmhart** [comment]
after poking around in the psc-ide it looks like it's possible to do a type request by identifier, I think this could be really useful,  perhaps the correct implementation is for pscid to provide a prompt which can be used to request a type from an identifier name (Probably this should be for top-level named expressions only).

@kritzcreek  - does this seem feasible/desireable? if so I'd be happy to implement this feature.

**Comment by kritzcreek** [comment]
I think at that point you should just be using one of the editor plugins? Those allow you to check out the type/go-to-definition for all top level identifiers via hovering in your source file. I can totally understand the desire for these features &mdash; they are the reason I built psc-ide in the first place, but they're easier to access in a more integrated fashion from within an editor.

`pscid` is meant as the tiniest as-little-configuration as possible tool for people that either didn't set up their editor yet or don't want to use an IDE like experience to write their code, I think adding a prompt is going to compromise that UX.

**Comment by Benjmhart** [comment]
fair enough,  can you recommend a vim plugin with this capability?

generally I came to pscid because of my enjoyment of the ghcid workflow

**Comment by kritzcreek** [comment]
I've heard good things about: https://github.com/neoclide/coc.nvim/wiki/Language-servers#purescript

That will also require that you put this on your path: https://github.com/nwolverson/purescript-language-server

**Comment by kritzcreek** [comment]
I'm assuming the editor plugin ended up doing what you needed.
