### ISSUE TITLE
Add command line option to output version

### ISSUE THREAD

**Issue by jkachmar** [kRITZCREEK/pscid#66]
It would be nice if `pscid` could print the version with something like `pscid --version` just as a sanity-check to make sure everything is in order.

Came up on justinwoo/easy-purescript-nix#108 when I wanted to very I had bumped everything correctly.

Sorry this isn't a PR, my local PS development setup isn't super great at the moment or I'd put something together myself since this is a small feature request.

I may try to open a PR this weekend, but also that's kind of the type of thing you see in a thousand open issues so uh... yeah.

**Comment by kritzcreek** [comment]
Thanks for the report, I should've done this a while ago. Should work in 2.9.3
