### ISSUE TITLE
Module `Data.String.CodeUnits` was not found.

### ISSUE THREAD

**Issue by 7c78** [kRITZCREEK/pscid#79]
After `spago install strings`, psci works OK but pscid issues an error.

![image](https://github.com/kritzcreek/pscid/assets/42330300/1575284a-e21b-4577-9b89-4f241411a9f7)

![image](https://github.com/kritzcreek/pscid/assets/42330300/ac041267-8590-4cb1-a019-202287476ade)

**Comment by kritzcreek** [comment]
You might need to run `spago build` once, before the language server behind `pscid` can pick up these new modules.

**Comment by 7c78** [comment]
@kritzcreek thanks. `spago build` fixes my problem. It turns out I did not install the `tuples` package.
